spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: 1aMCR3at1n6th15auth5y5t3mf0rmy5martworksp4c3b00k1ngapp
  expiration: 30000
  # 900000  # 15 min in ms

server:
  port: 8081