spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: https://your-eureka-url-on-render/eureka/